version: '3'
services:
  database:
    image: postgres:12
    restart: always
    ports:
        - "5432:5432"
    env_file:
        - ./.database.env
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
